#!/bin/bash

EXPLAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
DATABASE_NAME=$1
CONFIG_FILE=$2
VENV_DIR=$3

cd $VENV_DIR
source venv/bin/activate
elf_reader $DATABASE_NAME --config $CONFIG_FILE -q
deactivate
